### PR TITLE
1 no link to concept scheme

### LINKED ISSUE #1: NoLinkToConceptScheme is to restrictive
With https://github.com/skohub-io/skohub-vocabs/pull/230 we made it possible to only add one of the inverse relations '`hasTopConcept` or `topConceptOf` in SkoHub Vocabs. The Shape does not reflect this change yet and thus a build won't start in skohub-docker-vocabs:

https://github.com/skohub-io/shapes/blob/61d50c3046d157042e2581b8a48988dc64578044/skos.shacl.ttl#L156-L175

### PR DESCRIPTION
**Pull request by sroertgen**
I removed the shape in question and also added basic test functionality for the shape.

See https://github.com/skohub-io/shapes/tree/1-no-link-to-concept-scheme#tests for my idea of testing the shape.

### CODE REVIEW

**Comment by sroertgen** [comment]
I just came across this SHACL Test Suite report: https://w3c.github.io/data-shapes/data-shapes-test-suite/

If we would like to dig deeper into testing this shape, this might be an interesting option.

**Review by acka47 — COMMENTED** [review]
Aren't tests/valid/ConceptShape.ttl and tests/valid/OrphanConcepts.ttl identical? I don't see why we need both.

**Comment by sroertgen** [comment]
They are indeed identical. My idea (that I apparently did not write down) was that maybe a test file is added per shape to test that shape. So `OrpahnConcepts.ttl` should be the data to test the `:OrphanConcepts` shape and `ConceptShape.ttl` would be the data to test `:ConceptShape`.

**Comment by acka47** [comment]
It would probably reduce possible misunderstanding when the "Error" notes in by the test.sh script would include the filename where the error occured insteadof just "Error: This should be invalid, but is valid" referring to the previous line. (I at least was unsure to what this refers in the first try.)

**Review by acka47 — APPROVED** [review]
Generally, this looks fine. You may think about adressing my last comment but it is not necessary. I will have to understand this whole better in the future by taking a more thorough look at it.

**Comment by sroertgen** [comment]
That's a good point. I added the filename to the error message.

**Pull request merged**
